### RandomizedSearchCV:
RandomizedSearchCV is a technique that searches over random combinations of hyperparameters to find the best model configuration using cross-validation making it more efficient than exclusice methods.

To optimize computation, we primarily use **RandomizedSearchCV**

In [2]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report
from sklearn.datasets import make_classification
from sklearn.tree import DecisionTreeClassifier

X,y = make_classification(
    n_classes=2,
    n_informative=8,
    n_redundant=2,
    n_repeated=0,
    n_samples=1000,
    n_features=10,
    random_state=42,
    )

### GridSearchCV:

In [3]:
from sklearn.model_selection import GridSearchCV

clf = GridSearchCV( 
    DecisionTreeClassifier(),
    {
        'criterion' : ['gini', 'entropy'],
        'max_depth' : [5, 10, 15, 20]
    }, 
    cv = 5, 
    return_train_score= False
)

clf.fit(X, y)
df = pd.DataFrame(clf.cv_results_)
df

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_criterion,param_max_depth,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.007544,0.000848,0.001220,0.000268,gini,5,"{'criterion': 'gini', 'max_depth': 5}",0.775,0.795,0.735,0.805,0.775,0.777,0.024000,8
1,0.010772,0.000780,0.001002,0.000005,gini,10,"{'criterion': 'gini', 'max_depth': 10}",0.775,0.715,0.800,0.795,0.830,0.783,0.038288,6
2,0.011599,0.001021,0.001601,0.000801,gini,15,"{'criterion': 'gini', 'max_depth': 15}",0.775,0.725,0.810,0.810,0.825,0.789,0.035972,5
3,0.010460,0.000824,0.001430,0.000382,gini,20,"{'criterion': 'gini', 'max_depth': 20}",0.795,0.725,0.830,0.815,0.820,0.797,0.037762,3
4,0.011636,0.002250,0.001399,0.000483,entropy,5,"{'criterion': 'entropy', 'max_depth': 5}",0.765,0.785,0.745,0.815,0.785,0.779,0.023324,7
5,0.014194,0.000981,0.001010,0.000006,entropy,10,"{'criterion': 'entropy', 'max_depth': 10}",0.780,0.795,0.830,0.775,0.790,0.794,0.019339,4
6,0.014797,0.001165,0.001003,0.000005,entropy,15,"{'criterion': 'entropy', 'max_depth': 15}",0.765,0.805,0.815,0.795,0.865,0.809,0.032619,1
7,0.014995,0.001096,0.001203,0.000402,entropy,20,"{'criterion': 'entropy', 'max_depth': 20}",0.755,0.815,0.815,0.795,0.860,0.808,0.034000,2

As in grid search we had to calculate all of the permuation combinations which were 8 in this case. Which costs computation power. So to save computation power we use RandomizedSearchCV(). Which only calculates n_iter number of random combinations not all.

### RandomizedSearchCV:

In [5]:
from sklearn.model_selection import RandomizedSearchCV

clf = RandomizedSearchCV( 
    DecisionTreeClassifier(),
    {
        'criterion' : ['gini', 'entropy'],
        'max_depth' : [5, 10, 15, 20]
    }, 
    cv = 5, 
    return_train_score= False,
    n_iter=3
)

clf.fit(X, y)
df = pd.DataFrame(clf.cv_results_)
df

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_max_depth,param_criterion,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.007647,0.000906,0.001109,0.000670,5,gini,"{'max_depth': 5, 'criterion': 'gini'}",0.780,0.815,0.735,0.790,0.775,0.779,0.025962,3
1,0.010822,0.001135,0.001399,0.000485,20,gini,"{'max_depth': 20, 'criterion': 'gini'}",0.800,0.755,0.840,0.800,0.830,0.805,0.029665,1
2,0.010403,0.001023,0.000997,0.000011,5,entropy,"{'max_depth': 5, 'criterion': 'entropy'}",0.765,0.785,0.765,0.815,0.775,0.781,0.018547,2

As we can see that only random 3 of 8 combinations got calculated which saved a lot compuational power.

We can use all other methods of GridSearchCV as it is. Such as best_params, best_estimator, etc.

In [7]:
clf.best_params_

{'max_depth': 20, 'criterion': 'gini'}

In [8]:
clf.best_estimator_

DecisionTreeClassifier(max_depth=20)