In [1]:
import numpy as np
import pandas as pd
import scipy.stats as st

We have sample data for two test group 
1. Control Group : Old Drug Data
2. Test Group : New Drug Data

* Null : Both drugs has same avg recovery time (control_mean == test_mean)
* Alternate: New drug has better recovery time (control_mean < test_mean) (One-tailed test)(Right tailed)

In [2]:
control = pd.read_csv("control_group.csv")
print(control.shape)
control.head()

(130, 2)

  person_id  recovery_time_hrs
0      C001                4.4
1      C002                4.1
2      C003                3.2
3      C004                4.3
4      C005                4.9

In [3]:
test = pd.read_csv("test_group.csv")
print(test.shape)
test.head()

(100, 2)

  person_id  recovery_time_hrs
0      T001                3.7
1      T002                4.1
2      T003                3.7
3      T004                3.9
4      T005                3.7

In [7]:
control_mean = control.recovery_time_hrs.mean()
control_std = control.recovery_time_hrs.std()
control_size = control.shape[0]

control_mean, control_std, control_size

(np.float64(4.000769230769231), np.float64(0.4795825306420972), 130)

In [6]:
test_mean = test.recovery_time_hrs.mean()
test_std = test.recovery_time_hrs.std()
test_size = test.shape[0]

test_mean, test_std, test_size

(np.float64(3.9119999999999995), np.float64(0.31567788210852726), 100)

Let's find out Standerd error now using both the std

In [8]:
SE = np.sqrt((np.square(control_std)/control_size) + (np.square(test_std)/test_size))
SE

np.float64(0.05259041200457046)

In [10]:
z_score = (control_mean - test_mean)/SE
z_score

np.float64(1.6879356404646)

In [13]:
alpha = 0.05
z_critic = st.norm.ppf(1-alpha)
z_critic

np.float64(1.6448536269514722)

In [14]:
z_score, z_critic

(np.float64(1.6879356404646), np.float64(1.6448536269514722))

Since z_score > z_critic, We can reject Null Hypothesis. Therefore, New drug is found to be more effective and has better recovery time then old drug.